apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
data:
  EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID: {{ .Values.management.application.id | b64enc }}
  EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: {{ .Values.management.application.secret | b64enc }}
  {{- include "emqx.plugin.secret" . | nindent 2 }}
