{{- if .Values.ingress.enabled -}}
{{- if .Values.dashboard.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    # Now, ingress only supports dashboard service.
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: {{ .Values.ingress.pathType | default "ImplementationSpecific" }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "emqx.fullname" . }}-http
                port:
                  number: {{ .Values.service.http.ports.dashboard }}
              {{- else }}
              serviceName: {{ include "emqx.fullname" . }}-http
              servicePort: {{ .Values.service.http.ports.dashboard }}
              {{- end }}
    # TODO: Support ws and wss
{{- end }}
{{- end }}
