{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  # minAvailable: 1
  minAvailable: 50%
  selector:
    matchLabels:
      {{- include "emqx.selectorLabels" . | nindent 6 }}
{{- end }}
