apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
data:
  EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID: {{ .Values.management.application.id | b64enc }}
  EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: {{ .Values.management.application.secret | b64enc }}
  {{- if .Values.dashboard.enabled }}
  EMQX_DASHBOARD__DEFAULT_USER__LOGIN: {{ .Values.dashboard.defaultUsername | b64enc }}
  EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: {{ .Values.dashboard.defaultPassword | b64enc }}
  {{- end }}
  {{- if .Values.auth.username.enabled }}
  {{- include "emqx.auth.username" .Values.auth.username | nindent 2 }}
  {{- end }}
