apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}-http
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    {{- if .Values.service.http.ports.management }}
    - name: management
      port: {{ .Values.service.http.ports.management }}
      protocol: TCP
      targetPort: 8081
    {{- end }}
    {{- if .Values.service.http.ports.dashboard }}
    - name: dashboard
      port: {{ .Values.service.http.ports.dashboard }}
      protocol: TCP
      targetPort: 18083
    {{- end }}
  selector:
    {{- include "emqx.selectorLabels" . | nindent 4 }}
