apiVersion: v1
kind: Service
metadata:
  name: {{ include "emqx.fullname" . }}
  labels:
    {{- include "emqx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: mqtts
      port: 8883
      protocol: TCP
      targetPort: 8883
    - name: ws
      port: 8083
      protocol: TCP
      targetPort: 8083
    - name: wss
      port: 8084
      protocol: TCP
      targetPort: 8084
    - name: management
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: dashboard
      port: 18083
      protocol: TCP
      targetPort: 18083
  selector:
    {{- include "emqx.selectorLabels" . | nindent 4 }}
